---
log_file: "locutus.log"
broker_hosts:
  - tanagra
  - 61613
incoming_topics:
  - "lorax.timo.mount.broadcast"
  - "lorax.timo.camera.broadcast"
  - "lorax.timo.weather.broadcast"
  - "lorax.timo.locutus.dictrequest"
dictionary_request_topic: "lorax.timo.locutus.dictrequest"
dictionary_broadcast_topic: "lorax.timo.locutus.dictbroadcast"
message_wait_time: 0.1
redis_hostname: "tanagra"
redis_port: 6379
mount_storage:
  - "RA-J2000"
  - "dec-j2000"
  - "altitude"
  - "azimuth"
