---
agents_in_composite:
  - filterwheel:
      agent_name: IndiFilterWheel
      agent_protocol: IndiAgents
      dto_command_topic: lorax.timo.filterwheel.dto
      fw_host: morgan.lowell.edu
      fw_name: CCD Simulator
      fw_port: 7624
      incoming_topic: lorax.timo.dto.filterwheel
      outgoing_topic: lorax.timo.filterwheel.broadcast
      status:
        - FILTER_SLOT
        - FILTER_NAME
  - camera:
      agent_name: IndiCamera
      agent_protocol: IndiAgents
      camera_host: morgan.lowell.edu
      camera_name: CCD Simulator
      camera_port: 7624
      dto_command_topic: lorax.timo.camera.dto
      incoming_topic: lorax.timo.dto.camera
      outgoing_topic: lorax.timo.camera.broadcast
      status:
        - CCD_FRAME_TYPE
        - CCD_BINNING
        - CCD_GAIN
        - CCD_EXPOSURE
        - CCD_DIRECTORY_LOCATION
  - ccdcooler:
      agent_name: IndiCcdCooler
      agent_protocol: IndiAgents
      cooler_host: morgan.lowell.edu
      cooler_name: CCD Simulator
      cooler_port: 7624
      dto_command_topic: lorax.timo.ccdcooler.dto
      incoming_topic: lorax.timo.dto.ccdcooler
      outgoing_topic: lorax.timo.ccdcooler.broadcast
      status:
        - CCD_COOLER
        - CCD_TEMPERATURE
broker_hosts:
  - tanagra
  - 61613
log_file: CompositeAgent.log
message_wait_time: 0.5
