---
log_file: dto.log
broker_hosts:
  - tanagra
  - 61613
mount_command_topic: lorax.timo.dto.mount
mount_dto_topic: lorax.timo.mount.dto
camera_command_topic: lorax.timo.dto.camera
ccdcooler_command_topic: lorax.timo.dto.ccdcooler
fw_command_topic: lorax.timo.dto.filterwheel
camera_incoming_topic: lorax.timo.camera.broadcast
mount_type: PWI4
camera_type: INDI CCD_Simulator
command_input_file: command_test2
